version: '3.8'

services:
  web:
    image: websocket-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket-service
    ports:
      - "8010:8010"
    environment:
      - JWT_PUBLIC_KEY=asd
    volumes:
      - .:/app
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis  # Optional: set a password
    command: [ "redis-server", "--requirepass", "redis" ]
# Add other services here if needed, e.g., database
#    depends_on:
#      - services needed
#   Add needed network
#    networks:
#      - netowrk-example

#
#networks:
#  fastapi-network:
#    driver: bridge
